export enum Role {
  ROLE_ADMIN = "ROLE_ADMIN",
  ROLE_CONSULTANT = "ROLE_CONSULTANT",
  ROLE_MANAGER = "ROLE_MANAGER",
  ROLE_USER = "ROLE_USER",
  ROLE_ANONYMOUS = "ROLE_ANONYMOUS",
}

export enum PerimeterRole {
  PERIMETER_ADMIN = "PERIMETER_ADMIN",
  PERIMETER_MANAGER = "PERIMETER_MANAGER",
  PERIMETER_COLLABORATOR = "PERIMETER_COLLABORATOR",
  PERIMETER_CONTRIBUTOR = "PERIMETER_CONTRIBUTOR",
  PERIMETER_ANONYMOUS = "PERIMETER_ANONYMOUS",
  PERIMETER_WAITING_RESOLUTION = "PERIMETER_WAITING_RESOLUTION",
}
