export enum CefInputUnits {
  unit = "unit",
  L = "L",
  kg = "kg",
  km = "km",
  euro = "euro",
  keuro = "keuro",
  t = "t",
  squarem = "squarem",
  m3 = "m3",
  kWh = "kWh",
  kWhPCI = "kWhPCI",
  kWhPCS = "kWhPCS",
  tepPCI = "tepPCI",
  GJPCS = "GJPCS",
  GJPCI = "GJPCI",
  tkm = "tkm",
  kmpassenger = "kmpassenger",
  year = "year",
};