export enum ComputeMethodType {
  STANDARD = "STANDARD",
  CUSTOM_EMISSION_FACTOR = "CUSTOM_EMISSION_FACTOR",
  RAW_DATA = "RAW_DATA",
  // DEPRECATED
  DEPRECATED_EMISSION_FACTOR = "EMISSION_FACTOR",
};
