export enum TableSettingsTypes {
  SET_COLUMNS = "DATA_IMPORT_TABLE_SETTINGS_SET_COLUMNS",
  TOGGLE_COLUMN_VISIBILITY = "DATA_IMPORT_TABLE_SETTINGS_TOGGLE_COLUMN_VISIBILITY",
  MOVE_COLUMN_VIEW_RIGHT = "DATA_IMPORT_TABLE_SETTINGS_MOVE_COLUMN_VIEW_RIGHT",
  MOVE_COLUMN_VIEW_LEFT = "DATA_IMPORT_TABLE_SETTINGS_MOVE_COLUMN_VIEW_LEFT",
  SET_COLUMN_PAGE = "DATA_IMPORT_TABLE_SETTINGS_SET_COLUMN_PAGE",
  RESET = "DATA_IMPORT_TABLE_SETTINGS_RESET",
}
