export enum EntryDataSelectionTypes {
  SET_SELECTION = "DATA_IMPORT_ENTRY_DATA_SELECTION_SET_SELECTION",
  TOGGLE_ENTRY_DATA = "DATA_IMPORT_ENTRY_DATA_SELECTION_TOGGLE_ENTRY_DATA",
  SELECT_ALL = "DATA_IMPORT_ENTRY_DATA_SELECTION_SELECT_ALL",
  UNSELECT_ALL = "DATA_IMPORT_ENTRY_DATA_SELECTION_UNSELECT_ALL",
}
