export enum CustomEmissionFactorTypes {
  RESET_STATE = "CEF_RESET_STATE",
  REQUEST_FETCH_CUSTOM_EMISSION_FACTOR = "CEF_REQUEST_FETCH_CUSTOM_EMISSION_FACTOR",
  FETCHED_CUSTOM_EMISSION_FACTOR = "CEF_FETCHED_CUSTOM_EMISSION_FACTOR",
  REQUEST_UPDATE_CUSTOM_EMISSION_FACTOR = "CEF_REQUEST_UPDATE_CUSTOM_EMISSION_FACTOR",
  REQUEST_CREATION_CUSTOM_EMISSION_FACTOR = "CEF_REQUEST_CREATION_CUSTOM_EMISSION_FACTOR",
  END_CREATION = "CEF_END_CREATION",
  CUSTOM_EMISSION_FACTOR_CREATED = "CEF_CUSTOM_EMISSION_FACTOR_CREATED",
  ARCHIVE_REQUESTED = "CEF_ARCHIVE_REQUESTED",
  UNARCHIVE_REQUESTED = "CEF_UNARCHIVE_REQUESTED",
  CREATION_ERROR = "CEF_CREATION_ERROR",
}
