export enum DashboardsTypes {
  SET_SITES_FILTER = "SET_SITES_FILTER",
  SET_PRODUCTS_FILTER = "SET_PRODUCTS_FILTER",
  SET_OVERVIEW_TYPE = "SET_OVERVIEW_TYPE",
  TOGGLE_OVERVIEW_TYPE = "TOGGLE_OVERVIEW_TYPE",
  SET_CURRENT_VIEW = "SET_CURRENT_VIEW",
}
