export enum ListEntriesTypes {
    SELECT_ENTRIES = "LIST_ENTRIES_SELECT_ENTRIES",
    SELECT_ENTRIES_IN_ACTIVITY = "LIST_ENTRIES_SELECT_ENTRIES_IN_ACTIVITY",
    SELECT_ENTRIES_IN_SITE = "LIST_ENTRIES_SELECT_ENTRIES_IN_SITE"
}
