export enum CardExpansionTypes {
  CLOSE_ALL_CARDS = "CLOSE_ALL_CARDS",
  OPEN_ALL_CARDS = "OPEN_ALL_CARDS",
  TOGGLE_CARD = "TOGGLE_CARD",
  CLOSE_CARD = "CLOSE_CARD",
  OPEND_CARD = "OPEND_CARD",
}
