export enum ActivityCategoriesPreferencesType {
  SET_ALL_ACTIVITY_CATEGORIES_PREFERENCES = "SET_ALL_ACTIVITY_CATEGORIES_PREFERENCES",
  ACTIVITY_CATEGORIES_PREFERENCES_REQUESTED = "ACTIVITY_CATEGORIES_PREFERENCES_REQUESTED",

  ACTIVITY_CATEGORY_PREFERENCE_UPDATE_DESCRIPTION = "ACTIVITY_CATEGORY_PREFERENCE_UPDATE_DESCRIPTION",

  ACTIVITY_CATEGORY_PREFERENCE_UPDATE_ORDERS = "ACTIVITY_CATEGORY_PREFERENCE_UPDATE_ORDERS",
  ACTIVITY_CATEGORY_PREFERENCE_SAVE_ORDERS = "ACTIVITY_CATEGORY_PREFERENCE_SAVE_ORDERS",
  RESET_CATEGORY_PREFERENCES_STATE = "RESET_CATEGORY_PREFERENCES_STATE",
}
