export enum AuthTypes {
  LOGIN_RESET_ERRORS = "LOGIN_RESET_ERRORS",
  LOGIN_PASSWORD_ERROR = "LOGIN_PASSWORD_ERROR",
  LOGIN_EMAIL_ERROR = "LOGIN_EMAIL_ERROR",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGIN_BAD_CREDENTIALS_ERROR = "LOGIN_BAD_CREDENTIALS_ERROR",
  LOGIN_GENERIC_ERROR = "LOGIN_GENERIC_ERROR",
  AUTH_INFO = "AUTH_INFO",
  TOO_MANY_PASSWORD_ERRORS = "TOO_MANY_PASSWORD_ERRORS",
}
