export enum IndicatorTypes {
  SET_INDICATOR = "SET_INDICATOR",
  SET_CAMPAIGN_INDICATORS = "SET_CAMPAIGN_INDICATORS",
  REQUEST_FETCH_CAMPAIGN_INDICATORS = "REQUEST_FETCH_CAMPAIGN_INDICATORS",
  REQUEST_CREATE_DEFAULT_INDICATORS = "REQUEST_CREATE_DEFAULT_INDICATORS",
  REQUEST_CREATE_INDICATOR = "REQUEST_CREATE_INDICATOR",
  REQUEST_UPDATE_INDICATOR = "REQUEST_UPDATE_INDICATOR",
  REQUEST_DELETE_INDICATOR = "REQUEST_DELETE_INDICATOR",
}
