export enum ReglementationTablesTypes {
  REGLEMENTATION_TABLES_FETCH_REQUESTED = "REGLEMENTATION_TABLES_FETCH_REQUESTED",
  SET_REGLEMENTATION_TABLES = "SET_REGLEMENTATION_TABLES",
  REGLEMENTATION_TABLES_FETCH_FAILED = "REGLEMENTATION_TABLES_FETCH_FAILED",

  REGLEMENTATION_TABLES_CAMPAIGN_DATA_FETCH_REQUESTED = "REGLEMENTATION_TABLES_CAMPAIGN_DATA_FETCH_REQUESTED",
  REGLEMENTATION_TABLES_CAMPAIGN_DATA_FETCHED = "REGLEMENTATION_TABLES_CAMPAIGN_DATA_FETCHED",
  REGLEMENTATION_TABLES_CAMPAIGN_DATA_FETCH_FAILED = "REGLEMENTATION_TABLES_CAMPAIGN_DATA_FETCH_FAILED",
  REGLEMENTATION_TABLES_RESET_CAMPAIGN_DATA = "REGLEMENTATION_TABLES_RESET_CAMPAIGN_DATA",
}
