export enum UserTypes {
  SET_USERS = "CORE_USER_SET_USERS",
  IS_FETCHING = "CORE_USER_IS_FETCHING",
  FETCH_ERROR = "CORE_USER_FETCH_ERROR",
  ARCHIVE_REQUESTED = "CORE_USER_ARCHIVE_REQUESTED",
  UNARCHIVE_REQUESTED = "CORE_USER_UNARCHIVE_REQUESTED",
  UPDATE_FIRST_NAME_REQUESTED = "CORE_USER_UPDATE_FIRST_NAME_REQUESTED",
  UPDATE_LAST_NAME_REQUESTED = "CORE_USER_UPDATE_LAST_NAME_REQUESTED",
  UPDATE_DESCRIPTION_REQUESTED = "CORE_USER_UPDATE_DESCRIPTION_REQUESTED",
  CREATE_REQUESTED = "CORE_USER_CREATE_REQUESTED",
  CREATED = "CORE_USER_CREATED",
  CREATION_ERROR = "CORE_USER_CREATION_ERROR",
  CREATION_ERROR_REMOVED = "CORE_USER_CREATION_ERROR_REMOVED",
  RESET_USERS_STATE = "RESET_USERS_STATE",
  UPDATE_PERIMETER_ROLE_REQUESTED = "UPDATE_PERIMETER_ROLE_REQUESTED",
  SET_SEARCHED_USERS = "CORE_USER_SET_SEARCHED_USERS"
}
