export enum EmissionFactorTypes {
  FETCHED_COMPUTE_METHODS = "EF_FETCHED_COMPUTE_METHODS",
  REPLACE_EMISSION_FACTORS = "EF_REPLACE_EMISSION_FACTORS",
  AUTOCOMPLETE_REQUESTED = "EF_AUTOCOMPLETE_REQUESTED",
  AUTOCOMPLETE_FILLED = "EF_AUTOCOMPLETE_FILLED",
}
