export enum CoreSelectionTypes {
    SET_MULTIPLE_SELECTION = "CORE_SELECTION_SET_MULTIPLE_SELECTION",
    SET_SELECTION_SITE = "CORE_SELECTION_SET_SELECTION_SITE",
    SET_SELECTION_PRODUCT = "CORE_SELECTION_SET_SELECTION_PRODUCT"
}